### ISSUE TITLE
Extract all Vimeo video info into `_data/`

### ISSUE THREAD

**Issue by BigBlueHat** [RESTFest/videos.restfest.org#2]
Once #1 is done we can GET the videos info from Vimeo to kickstart the sites video content.

**Comment by BigBlueHat** [comment]
@Dashron I got this mostly working: https://github.com/RESTFest/videos.restfest.org/pull/5/commits/c834bfa4e3a3ffcba107382aecc585a1f750fcdc

Might be some sort of somewhat useful code in there for Vimeo demos or something...maybe. 😄

**Comment by Dashron** [comment]
:+1: :+1: :+1:

**Comment by BigBlueHat** [comment]
Done and in the repo.
